clear-host
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''
Write-Host -ForegroundColor Yellow ''

Write-Host -ForegroundColor Yellow ' _       ___           __                      ___                    '
Write-Host -ForegroundColor Yellow '| |     / (_)___  ____/ /___ _      _______   /   |  ____  ____  _____'
Write-Host -ForegroundColor Yellow '| | /| / / / __ \/ __  / __ \ | /| / / ___/  / /| | / __ \/ __ \/ ___/'
Write-Host -ForegroundColor Yellow '| |/ |/ / / / / / /_/ / /_/ / |/ |/ (__  )  / ___ |/ /_/ / /_/ (__  ) '
Write-Host -ForegroundColor Yellow '|__/|__/_/_/ /_/\__,_/\____/|__/|__/____/  /_/  |_/ .___/ .___/____/  '
Write-Host -ForegroundColor Yellow '                                                 /_/   /_/            '
Write-Host -ForegroundColor Yellow '======================================================================'
Get-AppxPackage -AllUsers| Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml”}


Write-Host -ForegroundColor Green 'Task Finished, press any key to return to previous menu...'
$HOST.UI.RawUI.ReadKey(“NoEcho,IncludeKeyDown”) | OUT-NULL
$HOST.UI.RawUI.Flushinputbuffer()